import {
  Wifi,
  ScanLine,
  Globe,
  ShieldAlert,
  Mail,
  Users,
  Search,
  Eye,
  FileText,
  Key,
  Lock,
  Code2,
  Brain,
  Bug,
  Cpu,
  Server,
  VenetianMask,
  FileSearch,
  BarChart3,
  Network,
  Zap,
  Database,
  AlertTriangle,
  Terminal,
  Radio,
  Shield,
} from "lucide-react";

export const SIDEBAR_MENU = [
  {
    category: "Network & WiFi",
    icon: Wifi,
    color: "#06b6d4",
    items: [
      { id: "wifi-analyzer", label: "WiFi Analyzer", icon: Wifi, path: "/modules/wifi-analyzer" },
      { id: "port-scanner", label: "Port Scanner", icon: ScanLine, path: "/modules/port-scanner" },
      { id: "packet-sniffer", label: "Packet Sniffer", icon: Radio, path: "/modules/packet-sniffer" },
      { id: "mitm", label: "MitM Attack", icon: Network, path: "/modules/mitm" },
      { id: "dns-tools", label: "DNS Tools", icon: Globe, path: "/modules/dns-tools" },
    ],
  },
  {
    category: "Social Engineering",
    icon: Users,
    color: "#a855f7",
    items: [
      { id: "phishing", label: "Phishing Manager", icon: Mail, path: "/modules/phishing" },
      { id: "social-engineering", label: "SE Toolkit", icon: Users, path: "/modules/social-engineering" },
      { id: "email-spoofing", label: "Email Spoofing", icon: AlertTriangle, path: "/modules/email-spoofing" },
    ],
  },
  {
    category: "OSINT",
    icon: Eye,
    color: "#eab308",
    items: [
      { id: "osint", label: "OSINT Framework", icon: Eye, path: "/modules/osint" },
      { id: "recon", label: "Reconnaissance", icon: Search, path: "/modules/recon" },
      { id: "metadata", label: "Metadata Extractor", icon: FileSearch, path: "/modules/metadata" },
    ],
  },
  {
    category: "Web Vulnerabilities",
    icon: ShieldAlert,
    color: "#f97316",
    items: [
      { id: "web-scanner", label: "Web Scanner", icon: ShieldAlert, path: "/modules/web-scanner" },
      { id: "sql-injection", label: "SQL Injection", icon: Database, path: "/modules/sql-injection" },
      { id: "xss", label: "XSS Suite", icon: Code2, path: "/modules/xss" },
      { id: "dir-bruteforce", label: "Dir Bruteforcer", icon: Server, path: "/modules/dir-bruteforce" },
    ],
  },
  {
    category: "Password & Auth",
    icon: Key,
    color: "#ef4444",
    items: [
      { id: "password-cracker", label: "Password Cracker", icon: Key, path: "/modules/password-cracker" },
      { id: "wordlist-generator", label: "Wordlist Forge", icon: FileText, path: "/modules/wordlist-generator" },
      { id: "credential-stuffing", label: "Credential Stuffing", icon: Lock, path: "/modules/credential-stuffing" },
    ],
  },
  {
    category: "Exploitation",
    icon: Zap,
    color: "#f43f5e",
    items: [
      { id: "exploit-db", label: "Exploit Database", icon: Database, path: "/modules/exploit-db" },
      { id: "payload-generator", label: "Payload Generator", icon: Terminal, path: "/modules/payload-generator" },
      { id: "privilege-escalation", label: "Priv Escalation", icon: Shield, path: "/modules/privilege-escalation" },
    ],
  },
  {
    category: "Crypto & Stego",
    icon: Lock,
    color: "#22c55e",
    items: [
      { id: "crypto", label: "Cryptography", icon: Lock, path: "/modules/crypto" },
      { id: "steganography", label: "Steganography", icon: FileText, path: "/modules/steganography" },
    ],
  },
  {
    category: "Forensics & Analysis",
    icon: Brain,
    color: "#3b82f6",
    items: [
      { id: "forensics", label: "Digital Forensics", icon: FileSearch, path: "/modules/forensics" },
      { id: "malware-analysis", label: "Malware Analysis", icon: Bug, path: "/modules/malware-analysis" },
      { id: "reverse-engineering", label: "Reverse Engineering", icon: Cpu, path: "/modules/reverse-engineering" },
      { id: "log-analyzer", label: "Log Analyzer", icon: BarChart3, path: "/modules/log-analyzer" },
    ],
  },
  {
    category: "Anonymous & Privacy",
    icon: VenetianMask,
    color: "#14b8a6",
    items: [
      { id: "anonymizer", label: "Anonymizer", icon: VenetianMask, path: "/modules/anonymizer" },
      { id: "darkweb", label: "Dark Web Monitor", icon: Globe, path: "/modules/darkweb" },
    ],
  },
  {
    category: "Reporting",
    icon: FileText,
    color: "#6366f1",
    items: [{ id: "reporting", label: "Report Generator", icon: FileText, path: "/modules/reporting" }],
  },
];
